costumer_manangement_system/chat/urls.py
from django.urls import path
from . import views

#Handles the URLs within the app

app_name = 'chat'

#paths
urlpatterns = [
    path('', views.chat_view, name='chat-start'),
    path('<username>/', views.get_or_createchatroom, name="start-chat"),
    path('room/<chatroom_name>/', views.chat_view, name="chatroom"),
    path('fileupload/<chatroom_name>/', views.chat_file_upload, name="chat-file-upload"),
    path('start/overview', views.chat, name='chat'),
    path('newchat/selecteduser', views.newchat_userinput, name='new-chat-userinput')
]

costumer_manangement_system/chat/models.py
from django.db import models
from accounts.models import CustomUser
import shortuuid

# Create your models here.

class ChatGroup(models.Model):
    group_name = models.CharField(max_length=128, unique=True, default=shortuuid.uuid)
    user_online = models.ManyToManyField(CustomUser, related_name='online_in_groups', blank=True)
    members = models.ManyToManyField(CustomUser, related_name='chat_groups',blank=True)
    is_private = models.BooleanField(default=False)

    def __str__(self):
        return self.group_name
    

class GroupMessage(models.Model):
    group = models.ForeignKey(ChatGroup, related_name='chat_message', on_delete=models.CASCADE)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    body = models.CharField(max_length=300, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    file = models.FileField(upload_to='chatfiles/', blank=True, null=True)

    def __str__(self) -> str:
        if self.body: 
            return f'{self.author.username} : {self.body}'
        else:
            return f'{self.author.username} : {self.file}'

    class Meta:
        ordering = ['-created']

costumer_manangement_system/chat/forms.py
from django.forms import ModelForm
from django import forms
from .models import *

class ChatmessageCreateForm(ModelForm):
    class Meta:
        model = GroupMessage
        fields = ['body']
        widgets = {
            'body': forms.TextInput(attrs={'placeholder': 'Add message...', 'maxlenght': '300', 'autofocus': True})
        }

costumer_manangement_system/chat/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .models import *
from django.contrib.auth.decorators import login_required
from .forms import ChatmessageCreateForm
from django.http import Http404, HttpResponse, HttpResponseForbidden
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync

# Create your views here.

@login_required
def chat_view(request, chatroom_name='public-chat'):
    chatroom_name = str(chatroom_name)
    chat_group, created = ChatGroup.objects.get_or_create(group_name=chatroom_name)
    chat_messages = chat_group.chat_message.all()[:30]
    form = ChatmessageCreateForm()

    other_user = None
    if chat_group.is_private:
        if request.user not in chat_group.members.all():
            print("Fehler aufgrund mangelnder Zugriffsrechte")
            raise HttpResponseForbidden("Keine Zugriffsrechte")
        for member in chat_group.members.all():
            if member != request.user:
                other_user = member
                break

    if request.headers.get('HX-Request'):
        form = ChatmessageCreateForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.author = request.user
            message.group = chat_group
            message.save()
            context = {
                'message': message,
                'user': request.user
            }
            return render(request, 'chat/partials/chat_message_p.html', context)
        
    context = {
        "chat_messages": chat_messages,
        "form": form, 
        "other_user": other_user,
        "chatroom_name": chatroom_name
    }
    return render(request, "chat/chat-home.html", context)

@login_required
def get_or_createchatroom(request, username):
    if request.user.username == username:
        return redirect('chat:chat-start')
    
    other_user = CustomUser.objects.get(username = username)
    my_private_chatrooms = request.user.chat_groups.filter(is_private=True)
    
    if my_private_chatrooms.exists():
        for chatroom in my_private_chatrooms:
            if other_user in chatroom.members.all():
                return redirect('chat:chatroom', chatroom_name = chatroom.group_name)
   
    chatroom = ChatGroup.objects.create( is_private = True )
    chatroom.members.add(other_user, request.user)   
    return redirect('chat:chatroom',chatroom_name = chatroom.group_name)

def chat_file_upload(request, chatroom_name):
    chat_group = get_object_or_404(ChatGroup, group_name = chatroom_name)

    if request.FILES:
        file = request.FILES['file']
        message = GroupMessage.objects.create(
            file = file,
            author = request.user,
            group = chat_group
        )

        channel_layer = get_channel_layer()
        event = {
            'type': 'message_handler',
            'message_id': message.id
        }
        async_to_sync(channel_layer.group_send)(
            chatroom_name, event
        )
    return HttpResponse()

@login_required
def chat(request):
    chats = ChatGroup.objects.filter(members = request.user)
    mychats = []
    for chat in chats:
        singlemembers = []
        members = CustomUser.objects.filter(chat_groups = chat)
        for member in members:
            if member == request.user:
                continue
            singlemembers.append(member.username)
        mychats.append([chat, singlemembers])
        

    return render(request, 'chat/chat.html', {"chats":mychats})

@login_required
def newchat_userinput(request):
    if request.method == 'POST':
        user = request.POST.get('username_chat')
        return redirect('chat:start-chat', username=user)
    return render(request, 'chat/create_new_chat.html')

costumer_manangement_system/chat/templates/chat/chat-home.html
{% extends "accounts/base.html" %}
{% block content %}
<div class="center-box">
        <h2>Chat</h2>
    <div>
        {% if other_user %}
        <p>Mit {{other_user}}</p>
        {%endif%}
    </div>
    <hr style="width: 80vw;">
    <div id="chatcontainer">
        <div id="onlinecountcontainer">
            {%include 'chat/partials/online_count.html'%}
        </div>
        <div id="chat_messages">
            {% for message in chat_messages reversed%}
            {%include 'chat/chat_message.html'%}
            {%endfor%}
        </div>
    </div>
    <div>
        <div class="center-box" style="margin-bottom: 5%;">
            <form id="chat_message_form" 
            hx-ect="ws"
            hx-trigger="submit"
            hx-target="#chat_messages"
            hx-swap="beforeend"
            onsubmit="sendMessage(event)">
            {% csrf_token %}
            {{ form.body }}
            <button type="submit" class="bt-green" style="margin-top: 1vh;">Text senden</button>
        </form>
        </div>
        <div>
            <form id="file_message_form" 
        method="post"
        enctype="multipart/form-data"
        hx-ect="ws"
        hx-trigger="submit"
        hx-target="#chat_messages"
        hx-swap="beforeend"
        onsubmit="uploadfile(event)">
            {%csrf_token%}
            <input type="file" name="file" id="id_file">
            <button type="submit" style="background-color: gainsboro; border: none; border-radius: 0.25rem; padding: 5px;">File Senden</button>
        </form>
        </div>
        
        
    </div>
</div>

<!-- Kontextdaten im HTML-Template einbetten -->
<script id="context-data" type="application/json">
    {{ chatroom_name }}
</script>
  
{% endblock %}

{%block javascript%}
<script>
     // JSON-Daten aus dem <script>-Tag lesen und in JavaScript verwenden
    const c_name = document.getElementById("context-data").textContent;
    const chatroom_name = c_name.trim()
    console.log("Chat Name",chatroom_name)

    // Liest die Chatroom-Daten aus dem JSON-Skript-Tag
    //kommunikation funktioniert an der stelle nicht/weil kontext falsch gelesen wird
    const protocol = window.location.protocol === "https:" ? "wss" : "ws";
    const chatSocket = new WebSocket(`${protocol}://${window.location.host}/ws/chatroom/${chatroom_name.toString()}`);

    // Sobald die WebSocket-Verbindung geöffnet ist
    chatSocket.onopen = function(e) {
        console.log('WebSocket-Verbindung geöffnet');
    };

    // Wenn eine Nachricht vom Server empfangen wird
    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        if (data.message_html) {
            document.getElementById('chat_messages').insertAdjacentHTML('beforeend', data.message_html);
        }
        if (data.online_count_html) {
        // Das <p>-Element aktualisieren, indem der HTML-Code ersetzt wird
        document.getElementById('online_count').outerHTML = data.online_count_html;
    }
    };

    // Wenn die Verbindung geschlossen wird
    chatSocket.onclose = function(e) {
        console.error('WebSocket-Verbindung geschlossen:', e);
    };

    // Funktion zum Senden von Nachrichten über WebSocket
    function sendMessage(event) {
        event.preventDefault(); // Verhindert das automatische Senden des Formulars
        const message = document.querySelector('input[name="body"]').value;
        chatSocket.send(JSON.stringify({ 'message': message }));
        document.querySelector('input[name="body"]').value = ''; // Eingabefeld zurücksetzen
    }
    
    function uploadfile(event){
        event.preventDefault();
        const formElement = event.target;
        const formData = new FormData(formElement); // Formulardaten sammeln
        
        // Senden des Formulars über fetch() an die definierte URL
    fetch(`/chat/fileupload/${chatroom_name}/`, {  // Die URL für den Datei-Upload anpassen
        method: "POST",
        body: formData,
        headers: {
            'HX-Request': 'true',  // Signalisiert HTMX-Anfrage
            'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value  // CSRF-Token hinzufügen
        }
    })
    .then(response => {
        if (response.ok) {
            console.log("Datei erfolgreich hochgeladen.");
            document.querySelector('input[name="file"]').value = ''; // Eingabefeld zurücksetzen

        } else {
            console.error("Fehler beim Hochladen der Datei.");
        }
    })
    .catch(error => console.error("Fehler beim Senden:", error));
    }
    
</script>
{%endblock%}

costumer_manangement_system/chat/templates/chat/chat.html
{% extends "accounts/base.html" %}
{%block content%}
<div class="center-box">
    <h1>Chats:</h1>
    <p>Public Chat:</p>
    <a href="/chat/" class="link-button" style="background-color: gainsboro;">Alle Benutzer</a>
    <p>Chat mit:</p>
    {%for element in chats%}
    {%if element.1%}
    <div class="center-box link-button">
    <a href="/chat/room/{{element.0}}">{{element.1 | join:", " }}</a>
    <small>Chat: {{element.0}}</small>
    </div>
    {%endif%}
    {%endfor%}
    <div>
        <small>oder</small>
        <hr style="width: 80vw;">
    </div>
    <div>
        <a href="{%url 'chat:new-chat-userinput'%}" class="link-button" style="background-color: #8CD2EE;">Neuen Chat erstellen</a>
    </div>
</div>
    
{%endblock content%}

costumer_manangement_system/chat/templates/chat/chat_message.html
{%if message.author == user%}

        <div class="messageself">
            <small>Von dir</small>
            {%if message.body == None%}
            <p>Dokument</p>
            {%else%}
            <p>{{message.body}}</p>
            {%endif%}
            {%if message.file%}
            <a href="{{message.file.url}}">Anhang 📄</a>
            {%endif%}
        </div>
{%else%}
        <div class="messageother">
            <small>von {{message.author}}</small>
            {%if message.body == None%}
            <p>Dokument</p>
            {%else%}
            <p>{{message.body}}</p>
            {%endif%}
            {%if message.file%}
            <a href="{{message.file.url}}" style="color: rgb(154, 154, 154);">Anhang 📄</a>
            {%endif%}
        </div>
        {%endif%}

costumer_manangement_system/chat/templates/chat/create_new_chat.html
{% extends "accounts/base.html" %}
{% block content %}
<div class="center-box">
    <h2>Neuen Chat erstellen: </h2>
    <p>Erstelle einfach einen neuen Chat mit einem User, indem du seinen Username eingibst</p>
    <form method="post">
        {%csrf_token%}
        <input type="text" name="username_chat">
        <button type="submit">Erstellen</button>
    </form>
</div>
    
{% endblock %}

costumer_manangement_system/chat/templates/chat/newchat.html
{% extends "accounts/base.html" %}
{%block content%}
    <div class="center-box">
        <p>Neuer Chat mit Josh:</p>
        <a href="{%url 'start-chat' profile.user.username %}">Click</a>
    </div>
{%endblock content%}